### ISSUE TITLE
Include Omnitone spatial audio

### ISSUE THREAD

**Issue by fulgorek** [thiagopnts/threejs360#1]
I'm trying to integrate Clapper-360 and Omnitone, can you provide more info about this Three.js build?

[Three-vr-omnitone
](https://github.com/danrossi/three-vr-omnitone)

[Omnitone Project
](https://github.com/GoogleChrome/omnitone)

**Comment by thiagopnts** [comment]
sorry just saw this issue now with the closed notification. So this build is basically a hand picked version of Three.js with exactly what we needed for doing 360. Back then three.js was structured in a way that was hard to build just a subset of it so we had to do through the files and only pick what we needed so we could have a small lib to do 360 video in our player
